version: '3.1'

services:

  nginx:
    container_name: 'nginx'
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

      - ./gbaranov/gbaranov-site:/usr/share/nginx/gbaranov/gbaranov-site/html
      - ./gbaranov/dh-param/dhparam-2048.pem:/etc/ssl/certs/gbaranov/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/gbaranov.com-0001/fullchain.pem:/etc/letsencrypt/live/gbaranov.com-0001/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/gbaranov.com-0001/privkey.pem:/etc/letsencrypt/live/gbaranov.com-0001/privkey.pem

    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
